### ISSUE TITLE
Error when running simulator

### ISSUE THREAD

**Issue by bcm0** [sontdhust/wandrian_src#1]
I run 
"roslaunch wandrian environment.launch world_file:=empty"
Followed by 
"roslaunch wandrian run_simulator.launch tool_size:=0 starting_point_x:=0 starting_point_y:=0"
Then I hit the r-Key to get it started.
I get the following error:
```
run: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = wandrian::environment::Map; typename boost::detail::sp_member_access<T>::type = wandrian::environment::Map*]: Assertion `px != 0' failed.
[run-4] process has died [pid 8864, exit code -6, cmd /home/ad/catkin_ws/devel/lib/wandrian/run run/power:=mobile_base/commands/motor_power run/velocity:=mobile_base/commands/velocity run/odometry:=odom run/laser:=scan __name:=run __log:=/home/ad/.ros/log/54cb0f00-5754-11e7-90a5-08002747d691/run-4.log].
log file: /home/ad/.ros/log/54cb0f00-5754-11e7-90a5-08002747d691/run-4*.log
```
Thank you for this code and for any help!

**Comment by sontdhust** [comment]
Sorry for the delay in replying your question.
You must pass the plan's name when execute the algorithm
Example:
```
roslaunch wandrian run_simulator.launch tool_size:=0.5 starting_point_x:=0.25 starting_point_y:=0.25 plan_name:=fss
```
Here `fss` stands for *Full Spiral STC*.

**Comment by bcm0** [comment]
Thank you very much for your answer @sontdhust.
Unfortunately I still get the same error.
I think  `Assertion px != 0 failed` is the problem. 
Most likely it's because of ROS Kinetic and Ubuntu 16.04.

```Available commands
---------------------------
p: Toggle power.
l: Toggle logging.
i: Get information
r: Start running.
c: Clear ros bag.
q: Quit.
[ INFO] [1498731074.609106432, 1761.644000000]: [Run]: Start running
run: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = wandrian::environment::Map; typename boost::detail::sp_member_access<T>::type = wandrian::environment::Map*]: Assertion `px != 0' failed.
[run-4] process has died [pid 31537, exit code -6, cmd /home/ad/wandrian/devel/lib/wandrian/run run/power:=mobile_base/commands/motor_power run/velocity:=mobile_base/commands/velocity run/odometry:=odom run/laser:=scan __name:=...
```

**Comment by sontdhust** [comment]
Hmmm... Maybe something gone wrong here...
Please follow these steps and notice me if you encounter that error again:
1. Check out to last commit at branch `master`:
```
$ git checkout master
$ git pull master
```

2. Start environment:
```
$ roslaunch wandrian environment.launch world_file:=world
```

3. Execute algorithm `fss` (stands for "full spiral stc"):
```
$ roslaunch wandrian run_simulator.launch tool_size:=0.5 starting_point_x:=0.25 starting_point_y:=0.25 plan_name:=fss
```

**Comment by adnion** [comment]
Thank you very much for this step by step guide. Got it working on Ubuntu Trusty 14.04 and ROS Indigo.

**Comment by canlang** [comment]
If there is no problem, I am curious to know how to modify the parameter to find the optimum value. Though the answer is difficult, thank you for helping me with a lot of sharing.

**Comment by sontdhust** [comment]
This project is now deprecated and we are working on plan to move it to new place:
- [Base](https://github.com/sontdhust/wandrian_base)
- Algorithms:
  - [STC](https://github.com/sontdhust/wandrian_stc)
  - [CCD Star](https://github.com/sontdhust/wandrian_ccd_star)
  ...

**Comment by sontdhust** [comment]
@zwkcoding So sorry! Since we were too busy last months, no algorithm got updated yet but we are trying our best!
Btw, you can still run `STC` at this repo, it will work without problem.

**Comment by zwkcoding** [comment]
OK, this is the best resource I have ever found in the internet by far. 
Best Thanks ! @sontdhust
